### PR TITLE
Transaction States Should Be Checked In Queue

### LINKED ISSUE #183: [bug] States should be checked in queue
**Describe the bug**

Currently, `MySqlConnection` checks transaction state between the `Mono.defer` is subscribed and `Exchangeable` is executed.

It may cause some undefined behavior. All states checking will have same problem, like `MySqlConnection.isSessionAutoCommit`.

I was thinking that transaction state is necessary, like [ConnectionImpl#rollback()](https://github.com/mysql/mysql-connector-j/blob/release/8.x/src/main/user-impl/java/com/mysql/cj/jdbc/ConnectionImpl.java#L1798) does, it even throws an exception if connection is not in a transaction.

Firstly, we should remove transaction state checking in `MySqlConnection`, see also #179 does.

Then we can consider adding proper status checks in `Exchangeable` and `RequestQueue`.

**Expected behavior**

States should be checked in `RequestQueue` executing `Exchangeable` instead.

### PR DESCRIPTION
**Pull request by jchrys**
Motivation:
Currently, `MySqlConnection` checks state between the `Mono.defer` is subscribed and `Exchangeable` is executed. It may cause undefined behavior.

Modification:
Checks transaction state when request queue executes task.

Result:
Resolves #183

### CODE REVIEW

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java [hunk 1]
```diff
@@ -265,19 +266,25 @@ static Mono<Void> beginTransaction(Client client, ConnectionState state, boolean
...
+        if (batchSupported) {
+            return client.exchange(new TransactionBatchExchangeable(commitStateSupplier)).then();
         }
 
-        return client.exchange(new TransactionMultiExchangeable(commitState)).then();
+        return client.exchange(new TransactionMultiExchangeable(commitStateSupplier)).then();
+    }
+
+    static Mono<Void> createSavepoint(Client client, ConnectionState state, String name, boolean batchSupported) {
+        Supplier<AbstractTransactionState> commitStateSupplier = () -> CreateSavepointState.of(state, name);
```
Comment (mirromutth) [inline src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: Maybe it should be `savepointState`

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java [hunk 2]
```diff
@@ -1227,16 +1234,63 @@ private static String buildStartTransaction(TransactionDefinition definition) {
...
+
+    private static final int CREATE_SAVEPOINT = 2;
+
+    private CreateSavepointState(ConnectionState state, int tasks, List<String> statements) {
+        super(state, tasks, statements);
+    }
+
+    @Override
+    boolean cancelTasks() {
+        return false;
```
Comment (mirromutth) [inline src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java:1236]: If it looks like following:

```java
@Override
boolean cancelTasks() {
    this.tasks = state.isInTransaction() ? CREATE_SAVEPOINT : START_TRANSACTION | CREATE_SAVEPOINT;

    return false;
}
```

Then `TransactionBatchExchangeable` or `TransactionMultiExchangeable` will check transaction state at `subscribe`, and `this.tasks` will be changed to the correct.

This avoids the use of `@Nullable state`, additional `Supplier`, and `assert`.

Or is there something else to consider?

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java [hunk 3]
```diff
@@ -1227,16 +1234,63 @@ private static String buildStartTransaction(TransactionDefinition definition) {
...
+    @Nullable
+    private AbstractTransactionState state;
+
+    TransactionBatchExchangeable(Supplier<AbstractTransactionState> stateSupplier) {
+        this.stateSupplier = stateSupplier;
     }
 
     @Override
     public void accept(ServerMessage message, SynchronousSink<Void> sink) {
+        assert state != null;
```
Comment (mirromutth) [inline src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: Maybe consider to use `cancelTasks` for avoid `Nullable` and `assert`?

**Comment by mirromutth** [comment]
Hmm, the naming of the method `cancelTasks` may hard to understand. Maybe we can consider changing it to `recalculateTasks` or `recalculateOrCancelTasks`

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java (hunk 2 above)
Comment (jchrys) [reply src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java:1236]: Nice feedback.  Let me change it :D

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java (hunk 1 above)
Comment (jchrys) [reply src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: done

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java [hunk 4]
```diff
@@ -72,9 +72,11 @@
 import java.util.Iterator;
 import java.util.List;
 import java.util.Map;
+import java.util.Objects;
 import java.util.concurrent.atomic.AtomicBoolean;
 import java.util.function.Consumer;
 import java.util.function.Predicate;
+import java.util.function.Supplier;
```
Comment (mirromutth) [inline src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: It should be unused import

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java [hunk 5]
```diff
@@ -1075,26 +1089,18 @@ protected boolean process(int task, SynchronousSink<Void> sink) {
...
-            List<String> statements = new ArrayList<>(2);
-
-            statements.add("SET innodb_lock_wait_timeout=" + lockWaitTimeout);
-            statements.add(doneSql);
-
-            return new CommitRollbackState(state, LOCK_WAIT_TIMEOUT | COMMIT_OR_ROLLBACK, statements);
-        }
-
-        return new CommitRollbackState(state, COMMIT_OR_ROLLBACK, Collections.singletonList(doneSql));
+    static CommitRollbackState of(ConnectionState state, boolean commit) {
```
Comment (mirromutth) [inline src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: Maybe just use constructor instead of a static method, because we calculate statements in `cancelTasks` now.

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java [hunk 6]
```diff
@@ -1106,25 +1112,37 @@ final class StartTransactionState extends AbstractTransactionState {
 
     private static final int START_TRANSACTION = 4;
 
-    private final long lockWaitTimeout;
-
-    @Nullable
-    private final IsolationLevel isolationLevel;
+    private static final int CANCEL = 8;
```
Comment (mirromutth) [inline src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java:1109]: I'm not sure if the `CANCEL` flag is necessary. Currently, if `cancelTasks` returns `true`, that means "cancel the current request/exchange", then `CANCEL` flag will not be actually used.

So I think we can just remove the flag, and use `0` for the bitmap value if it should be cancelled.

Or if the `CANCEL` flag should be used, we can change `cancelTasks` to return `void`, then make `TransactionBatchExchangeable#subscribe` and `TransactionMultiExchangeable#subscribe` check the calculated flags instead of the return value.

**Review by mirromutth — COMMENTED** [review]
Good idea, it makes sense to calculate statements and task bitmaps in same method.

I think it's ready to be merged for now, but maybe it could use a little more polish?

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java (hunk 6 above)
Comment (jchrys) [reply src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java:1109]: The current implementation sends a `PING` client message when `cancelTasks` returns `true` and processes a `ServerMessage` with the `START_TRANSACTION` task flag turned on. I just separated the flag into `START_TRANSACTION` and `CANCEL` to make flags more clear.

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java (hunk 5 above)
Comment (jchrys) [reply src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: Sure, Thanks!

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java (hunk 4 above)
Comment (jchrys) [reply src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: done

**Comment by jchrys** [comment]
> Good idea, it makes sense to calculate statements and task bitmaps in same method.
> 
> I think it's ready to be merged for now, but maybe it could use a little more polish?

Refined the code to enhance clarity and reduced the reliance on `AbstractTransactionState`. 
Please review, and please let me know if want to revert to the latest version.

**Comment by jchrys** [comment]
> Good idea, it makes sense to calculate statements and task bitmaps in same method.
> 
> I think it's ready to be merged for now, but maybe it could use a little more polish?

Sure, I think we could address the known issue first and then work on further polishing it.
@mirromutth @JohnNiang PTAL

File: src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java [hunk 7]
```diff
@@ -983,26 +989,20 @@ abstract class AbstractTransactionState {
      * A bitmap of unfinished tasks, the lowest one bit is current task.
      */
     int tasks;
-
-    private final List<String> statements;
+    List<String> statements = new ArrayList<>(5);
```
Comment (jchrys) [inline src/main/java/io/asyncer/r2dbc/mysql/QueryFlow.java]: final
