### PR TITLE
Utilize collationId for MySqlType Identification

### LINKED ISSUE #91: [bug] JSON type breaks when UNION query
**Describe the bug**
- when `UNION` query is used mysql `JSON` type breaks into `BLOB`
- conversion to a `String` breaks
```java
java.lang.IllegalArgumentException: Cannot decode class java.lang.String for BLOB

	at io.asyncer.r2dbc.mysql.codec.DefaultCodecs.decodeNormal(DefaultCodecs.java:226)
	at io.asyncer.r2dbc.mysql.codec.DefaultCodecs.decode(DefaultCodecs.java:110)
	at io.asyncer.r2dbc.mysql.MySqlRow.get(MySqlRow.java:69)
	at com.infrastructure.db.R2dbcMysqlIT.lambda$errorWhenUnionQuery$2(R2dbcMysqlIT.java:86)
	at io.asyncer.r2dbc.mysql.MySqlResult.lambda$map$2(MySqlResult.java:113)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:193)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at io.asyncer.r2dbc.mysql.internal.util.DiscardOnCancelSubscriber.onNext(DiscardOnCancelSubscriber.java:66)
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:670)
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:748)
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:790)
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:268)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at io.asyncer.r2dbc.mysql.internal.util.DiscardOnCancelSubscriber.onNext(DiscardOnCancelSubscriber.java:66)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128)
	at com.sdk.context.logging.MdcContextLifter.onNext(MdcContextLifter.java:30)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537)
	at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343)
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)
	at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:309)
	at io.asyncer.r2dbc.mysql.client.ReactorNettyClient$ResponseSink.next(ReactorNettyClient.java:355)
	at io.asyncer.r2dbc.mysql.client.ReactorNettyClient.lambda$new$0(ReactorNettyClient.java:113)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:294)
	at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:403)
	at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.asyncer.r2dbc.mysql.client.MessageDuplexCodec.handleDecoded(MessageDuplexCodec.java:178)
	at io.asyncer.r2dbc.mysql.client.MessageDuplexCodec.channelRead(MessageDuplexCodec.java:81)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**To Reproduce**
```java
package com.infrastructure.db;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;

import java.util.List;

import static java.util.Objects.requireNonNull;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertIterableEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@SpringBootTest
public class R2dbcMysqlIT {

  @Autowired
  private DatabaseClient databaseClient;

  @BeforeEach
  void setUp() {
    var initDb = """
        create schema r2dbc_mysql_test;
        use r2dbc_mysql_test;
        create table phone_call (id int not null, agents json not null);
        insert into phone_call values(1, '[{"id" : "1", "name": "agent_1"}, {"id" : "2", "name": "agent_2"}]');
        insert into phone_call values(2, '[{"id" : "3", "name": "agent_3"}]');
        """;
    databaseClient.sql(initDb)
        .then()
        .block();
  }

  @AfterEach
  void tearDown() {
    var cleanDb = "drop schema r2dbc_mysql_test;";
    databaseClient.sql(cleanDb)
        .then()
        .block();
  }

  @Test
  void noErrorWhenSimpleQuery() {
    var expected = List.of(
        new Agent(1, "agent_1"),
        new Agent(2, "agent_2"),
        new Agent(3, "agent_3"));
    var query = "select * from r2dbc_mysql_test.phone_call;";
    var agentListType = new TypeToken<List<Agent>>(){}.getType();
    List<PhoneCall> phoneCalls = databaseClient.sql(query)
        .map(row -> new PhoneCall(
            requireNonNull(row.get("id", Integer.class)),
            new Gson().fromJson(row.get("agents", String.class), agentListType)))
        .all()
        .collectList()
        .block();
    assertNotNull(phoneCalls);
    assertEquals(2, phoneCalls.size());
    assertIterableEquals(expected, phoneCalls.stream().flatMap(p -> p.agents.stream()).toList());
  }

  @Test
  void errorWhenUnionQuery() {
    var expected = List.of(
        new Agent(1, "agent_1"),
        new Agent(2, "agent_2"),
        new Agent(3, "agent_3"));
    var query = """
        (select * from r2dbc_mysql_test.phone_call
        where id = 1)
        union
        (select * from r2dbc_mysql_test.phone_call
        where id = 2);
        """;
    var agentListType = new TypeToken<List<Agent>>(){}.getType();
    List<PhoneCall> phoneCalls = databaseClient.sql(query)
        .map(row -> new PhoneCall(
            requireNonNull(row.get("id", Integer.class)),
            new Gson().fromJson(row.get("agents", String.class), agentListType)))
        .all()
        .collectList()
        .block();
    assertNotNull(phoneCalls);
    assertEquals(2, phoneCalls.size());
    assertIterableEquals(expected, phoneCalls.stream().flatMap(p -> p.agents.stream()).toList());
  }

  private static class PhoneCall {
    int id;
    List<Agent> agents;

    PhoneCall(int id, List<Agent> agents) {
      this.id = id;
      this.agents = agents;
    }
  }

  private static class Agent {
    int id;
    String name;

    Agent(int id, String name) {
      this.id = id;
      this.name = name;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) return true;
      if (!(o instanceof Agent agent)) return false;

      if (id != agent.id) return false;
      return name.equals(agent.name);
    }

    @Override
    public int hashCode() {
      int result = id;
      result = 31 * result + name.hashCode();
      return result;
    }
  }
}
```

**Expected behavior**
Conversion from `JSON` mysql type to `String` java type works with `UNION` queries.

**Screenshots**
**asyncer_simple_query**
asyncer_simple_query_string_codec
**asyncer_union_query**
asyncer_union_query_string_codec
**miku_union_query**
miku_union_query_string_codec
**tested versions**
mysql_version
`io.asyncer:r2dbc-mysql:1.0.0`  
`dev.miku:r2dbc-mysql:0.8.2.RELEASE`

**Additional context**
It seems that the implementation of `StringCodec` has changed. Conversion works fine for `dev.miku:r2dbc-mysql:0.8.2.RELEASE`. Also conversion works as well for `org.mariadb:r2dbc-mariadb:1.1.4`.

### PR DESCRIPTION
**Pull request by jchrys**
Motivation:
varchar binary, the union of JSON and char binary columns are not being accurately mapped to the appropriate MySqlType.

Modification:
Use collationId(charset id) to identify mysql type.

Result:
Enhanced MySqlType Identification.
Resolves #91

### CODE REVIEW

**Comment by jchrys** [comment]
need to change `ColumnDefinition.toString()` + `equals()`

File: src/main/java/io/asyncer/r2dbc/mysql/ColumnDefinition.java [hunk 1]
```diff
@@ -137,6 +145,10 @@ public String toString() {
      * @return the {@link ColumnDefinition} without unknown or useless flags.
      */
     public static ColumnDefinition of(int definitions) {
-        return new ColumnDefinition((short) (definitions & ALL_USED));
+        return new ColumnDefinition((short) (definitions & ALL_USED), 0);
+    }
+
+    public static ColumnDefinition of(int definitions, int collationId) {
```
Comment (jchrys) [inline src/main/java/io/asyncer/r2dbc/mysql/ColumnDefinition.java:165]: Need to add comment why we need this
